services:
  auth-services:
    container_name: auth-services
    restart: always
    build:
      context: ../
      dockerfile: ./src/auth-service/Dockerfile
    environment:
      USER_HOST: user-services
      PRODUCT_HOST: product-services
      ORDER_HOST: order-services
    expose:
      - 8080
    ports:
     - ${AUTH_SERVICES_PORT}:${AUTH_SERVICES_PORT}
    depends_on:
      - mongodb
    volumes:
      - ../src/auth-service/:/app/src/auth-service/

  mongodb:
    container_name: db
    image: mongo:latest
    restart: always
    ports:
    - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongodb-data:/data/db
      - ../db/MongoDB/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

volumes:
  mongodb-data: