services:
  mongodb:
    container_name: db
    image: mongo:latest
    restart: always
    ports:
    - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongodb-data:/data/db
      - ../db/MongoDB/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  # account-employee-services:
  #   container_name: account-employee-services
  #   restart: always
  #   build:
  #     ctx: ../
  #     dockerfile: ./src/account-employee-service/Dockerfile
  #   environment:
  #     POSTGRES_HOST: account-employee-db
  #   expose:
  #     - 8080
  #   ports:
  #    - ${Account_SERVICES_PORT}:${Account_SERVICES_PORT}
  #   depends_on:
  #     - account-employee-db
  #   volumes:
  #     - ../src/account-employee-service/:/app/src/account-employee-service/

volumes:
  mongodb-data: